services:
  - type: web
    name: citizen-complaint-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: mongodb+srv://huyousfisoft_db_user:YKIiHFGHj0tDEE6r@cluster0.jmvgzzy.mongodb.net/citizen_portal?appName=Cluster0&retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: http://localhost:5173
